CREATE TABLE book
(
    ID             INTEGER IDENTITY PRIMARY KEY,
    NAME           VARCHAR(256)   NOT NULL,
    ISBN           VARCHAR(16)    NOT NULL,
    PRICE          DECIMAL(10, 2) NOT NULL,
    PUBLISHED_DATE DATE           NOT NULL
);

CREATE TABLE author
(
    ID            INTEGER IDENTITY PRIMARY KEY,
    FIRST_NAME    VARCHAR(128) NOT NULL,
    LAST_NAME     VARCHAR(128) NOT NULL,
    DATE_OF_BIRTH DATE         NOT NULL,
);

CREATE TABLE book_author
(
    BOOK   INTEGER NOT NULL,
    AUTHOR INTEGER NOT NULL,
    FOREIGN KEY (BOOK) REFERENCES book (ID),
    FOREIGN KEY (AUTHOR) REFERENCES author (ID)
)
