CREATE TABLE book
(
    ID             BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME           VARCHAR(256)   NOT NULL,
    ISBN           VARCHAR(16)    NOT NULL,
    PRICE          DECIMAL(10, 2) NOT NULL,
    PUBLISHED_DATE DATE           NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE author
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME    VARCHAR(128) NOT NULL,
    LAST_NAME     VARCHAR(128) NOT NULL,
    DATE_OF_BIRTH DATE         NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE book_author
(
    BOOK   BIGINT NOT NULL,
    AUTHOR BIGINT NOT NULL,
    CONSTRAINT FOREIGN KEY (BOOK) REFERENCES book (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (AUTHOR) REFERENCES author (ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;
